version: '3.8'
services:
  web:
    build: .
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: scraping
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: scraping
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234